namespace Registration.ApplicationCode.Other.FCConfiguration;

public enum FCType
{
    GRADIENT_FEATURE_COMPUTER,
    CURVATURE_FEATURE_COMPUTER,
    PCA_FEATURE_COMPUTER,
    QUANTILES_FEATURE_COMPUTER,
    POINT_VALUE_FEATURE_COMPUTER,
    SPHERICAL_HARMONICS_FEATURE_COMPUTER,
    SHAPE_INDEX_FEATURE_COMPUTER
}